// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Provides a Genkit flow for summarizing PDF documents. 
 *
 * - pdfSummarizer - A function that accepts PDF content and returns a summary.
 * - PdfSummarizerInput - The input type for the pdfSummarizer function.
 * - PdfSummarizerOutput - The return type for the pdfSummarizer function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const PdfSummarizerInputSchema = z.object({
  pdfDataUri: z
    .string()
    .describe(
      "The PDF document content as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});
export type PdfSummarizerInput = z.infer<typeof PdfSummarizerInputSchema>;

const PdfSummarizerOutputSchema = z.object({
  summary: z.string().describe('A concise summary of the PDF document.'),
});
export type PdfSummarizerOutput = z.infer<typeof PdfSummarizerOutputSchema>;

export async function pdfSummarizer(input: PdfSummarizerInput): Promise<PdfSummarizerOutput> {
  return pdfSummarizerFlow(input);
}

const pdfSummarizerPrompt = ai.definePrompt({
  name: 'pdfSummarizerPrompt',
  input: {schema: PdfSummarizerInputSchema},
  output: {schema: PdfSummarizerOutputSchema},
  prompt: `Sen, karmaşık belgelerden detaylı ve anlaşılır özetler çıkarmada uzman bir yapay zekasın. Görevin, sağlanan PDF belgesinin kapsamlı ve yapılandırılmış bir Türkçe özetini oluşturmaktır. Belgenin yazarı veya dersin konusu gibi meta verileri yok sayarak doğrudan içeriğin kendisine, ana başlığa ve genel konu başlıklarına odaklan.

Lütfen aşağıdaki adımları izle:
1.  Belgedeki tüm ana başlıkları ve alt başlıkları dikkatlice belirle.
2.  Her bir konu başlığını detaylı bir şekilde irdele. Ana fikirleri, önemli noktaları, kilit kavramları ve destekleyici örnekleri belirleyerek her konu için ayrı başlıklar altında derinlemesine bir özet çıkar.
3.  Özet içeriğini, belirlediğin başlıklara göre yapılandır. Her konu başlığı için ayrı paragraflarda, ayrıntılı ve anlaşılır bir dille bir özet yaz, başlıklar arasında boşluklar bırak. Yüzeysel bir yaklaşımdan kaçın.
4.  Tüm metnin Türkçe olduğundan emin ol.

PDF Belgesi: {{media url=pdfDataUri}}`,
});

const pdfSummarizerFlow = ai.defineFlow(
  {
    name: 'pdfSummarizerFlow',
    inputSchema: PdfSummarizerInputSchema,
    outputSchema: PdfSummarizerOutputSchema,
  },
  async input => {
    const {output} = await pdfSummarizerPrompt(input);
    return output!;
  }
);
